#!/bin/bash
APPSPATH=~/.local/share/applications
WINDOW=hideapps-screen
echo '#!/bin/bash' > $WINDOW
chmod +x $WINDOW
echo 'yad --title "Hide Apps" --form --scroll\' >> $WINDOW
 
for FILE in $(ls -1 $APPSPATH/waydroid*desktop)
do
STATE=$(grep NoDisplay $FILE)
#NAME=$(echo $FILE | cut -d "." -f2- | rev | cut -d "." -f2- | rev)
NAME=$(grep Name $FILE | cut -d "=" -f2-)
    case $STATE in
        "" )
           echo 'NoDisplay=false' >> $FILE
           echo "    --field='$NAME (visible)':fbtn \"sed -i '/NoDisplay/ s/false/true/' $FILE\" \\" >> $WINDOW ;;

        "NoDisplay=false" )
           echo "    --field='$NAME (visible)':fbtn \"sed -i '/NoDisplay/ s/false/true/' $FILE\" \\" >> $WINDOW ;;
           
        "NoDisplay=true" )
           echo "    --field='$NAME (hidden)':fbtn \"sed -i '/NoDisplay/ s/true/false/' $FILE\" \\" >> $WINDOW ;;
    esac
done
echo "  --button='Close!gtk-cancel':1" >> $WINDOW
bash $WINDOW
