#!/bin/bash
wget -q --spider https://1.1.1.1
if [ $? -eq 0 ]; then
echo "Updating repos..."
echo $1 | sudo -S apt update
else
   echo "You appear to be offline."
   echo "You should establish an internet connection and try again."
   exit 1
fi
sudo apt install curl wget lxc python3 -y
sudo apt install ca-certificates -y
export DISTRO="bullseye" && \
sudo curl -# --proto '=https' --tlsv1.2 -Sf https://repo.waydro.id/waydroid.gpg --output /usr/share/keyrings/waydroid.gpg && \
echo "deb [signed-by=/usr/share/keyrings/waydroid.gpg] https://repo.waydro.id/ $DISTRO main" > ~/waydroid.list && \
sudo mv ~/waydroid.list /etc/apt/sources.list.d/waydroid.list && \
sudo apt update
sudo apt -y install waydroid
sudo waydroid init
sudo systemctl start waydroid-container
#   sudo systemctl disable android_boot_completed.service
echo ""
echo "Installed Waydroid."
