#!/bin/bash
waydroid session stop
echo $1 | sudo -S waydroid container stop
sudo apt remove waydroid -y
sudo rm -rf /var/lib/waydroid /home/.waydroid ~/waydroid ~/.share/waydroid ~/.local/share/applications/*aydroid* ~/.local/share/waydroid
